!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 0, z: 0.5} #agent position
      - !Item
        name: GoodGoal
        positions:
        - !Vector3 {x: 6, y: 0, z: 34} #goal position
        sizes:
        - !Vector3 {x: 0.8, y: 0.8, z: 0.8} #goal size
